use_frameworks!

target 'ZHTableViewGroupSwift_Example' do
  pod 'ZHTableViewGroupSwift', :path => '../'
  pod 'SnapKit', '~> 3.2.0'
  target 'ZHTableViewGroupSwift_Tests' do
    inherit! :search_paths

    
  end
end
