project 'iOS Example.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'iOS Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'ZHTableViewGroupSwift', :path => '../'
  # Pods for iOS Example

end
