project 'SwiftTableViewGroupApp-CocoaPods.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'SwiftTableViewGroupApp-CocoaPods' do
  pod 'SwiftTableViewGroup', :path => "../SwiftTableViewGroup.podspec"
end
